FROM node:20-alpine

WORKDIR /app

# Instalar dependências
COPY package.json package-lock.json* ./
RUN npm ci

# Copiar o restante dos arquivos
COPY . .

# Expor a porta 3000
EXPOSE 3000

# Definir host para permitir acesso externo ao container
ENV HOSTNAME "0.0.0.0"

# Iniciar em modo de desenvolvimento
CMD ["npm", "run", "dev"]
